#!/usr/bin/env ruby

git_path = File.expand_path("../.git", __dir__)

if File.exist?(git_path)
  lib_path = File.expand_path("../lib", __dir__)
  $:.unshift(lib_path)
end

require 'derivator'

puts Derivator::Mnemonic.generate
